#!/bin/fish


inotifywait -e modify,create,delete,move -rm .|while read dir action file
    if echo "$dir"|grep -vq "target/"
        echo "$dir $action $file"
        if echo "$file"|grep -q "htsx"
            if echo "$action"|grep -q -e "CREATE" -e "MOVE_TO" -e "MODIFY"
                cargo run --release -- convert -p "$dir$file"
            else if echo "$action"|grep -q "MOVE_FROM"
                /bin/rm (echo "$dir$file"|sed "s/htsx\$/html/")
            else if echo "$action"|grep -q "DELETE"
                /bin/rm (echo "$dir$file"|sed "s/htsx\$/html/")
            end
        else if echo "$file"|grep -q "cssx"
            if echo "$action"|grep -q -e "CREATE" -e "MOVE_TO" -e "MODIFY"
                cargo run --release -- convert "$dir$file"
            else if echo "$action"|grep -q "MOVE_FROM"
                /bin/rm (echo "$dir$file"|sed "s/cssx\$/css/")
            else if echo "$action"|grep -q "DELETE"
                /bin/rm (echo "$dir$file"|sed "s/cssx\$/css/")
            end
        end
    end
end
